import { StyleSheet } from 'react-native';

import { COLORS } from './theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  authSafe: { flex: 1, backgroundColor: COLORS.paper },
  appSafe: { flex: 1, backgroundColor: COLORS.paper },
  authContent: { flexGrow: 1, paddingHorizontal: 28, justifyContent: 'center', paddingVertical: 32 },
  brandMark: { width: 68, height: 68, borderRadius: 18, backgroundColor: COLORS.navy, alignItems: 'center', justifyContent: 'center', marginBottom: 18 },
  brand: { fontSize: 18, fontWeight: '800', color: COLORS.navy, letterSpacing: 0 },
  authTitle: { color: COLORS.ink, fontSize: 29, fontWeight: '800', marginTop: 22 },
  authSubtitle: { color: COLORS.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 22 },
  roleSelector: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  roleOption: { flex: 1, minHeight: 46, borderRadius: 8, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  roleOptionActive: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  roleOptionText: { color: COLORS.blue, fontSize: 12, fontWeight: '800' },
  roleOptionTextActive: { color: COLORS.white },
  fieldWrap: { marginBottom: 14 },
  fieldLabel: { color: COLORS.ink, fontSize: 13, fontWeight: '700', marginBottom: 7 },
  fieldLabelError: { color: COLORS.red },
  input: { height: 50, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, paddingHorizontal: 14, fontSize: 15, color: COLORS.ink },
  passwordInputWrap: { height: 50, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, paddingLeft: 14, paddingRight: 6, flexDirection: 'row', alignItems: 'center' },
  passwordInput: { flex: 1, height: '100%', fontSize: 15, color: COLORS.ink },
  passwordToggle: { width: 42, height: 42, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  inputError: { borderColor: COLORS.red, backgroundColor: '#FFF6F6' },
  fieldErrorText: { color: COLORS.red, fontSize: 12, fontWeight: '600', marginTop: 5 },
  primaryButton: { minHeight: 51, backgroundColor: COLORS.blue, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginTop: 8 },
  buttonDisabled: { opacity: 0.72 },
  primaryButtonText: { color: COLORS.white, fontSize: 15, fontWeight: '800' },
  demoHint: { textAlign: 'center', color: COLORS.muted, fontSize: 12, marginTop: 24 },
  errorText: { color: COLORS.red, fontSize: 13, marginBottom: 10 },
  screen: { flex: 1 },
  scrollPad: { padding: 20, paddingBottom: 108 },
  header: { paddingHorizontal: 20, paddingTop: 19, paddingBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerText: { flex: 1, paddingRight: 12 },
  eyebrow: { color: COLORS.blue, fontSize: 11, fontWeight: '800', letterSpacing: 0.5, marginBottom: 4 },
  pageTitle: { color: COLORS.ink, fontSize: 25, fontWeight: '800' },
  todayCard: { marginHorizontal: 20, backgroundColor: COLORS.navy, borderRadius: 8, padding: 18 },
  todayTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  todayLabel: { color: '#B5D5FF', fontWeight: '800', fontSize: 11, letterSpacing: 0.5 },
  todayCourse: { color: COLORS.white, fontSize: 20, fontWeight: '800', marginTop: 6 },
  todayInfo: { color: '#D7E7FC', fontSize: 13, marginTop: 5 },
  teacherHero: { marginHorizontal: 20, backgroundColor: COLORS.navy, borderRadius: 8, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 },
  teacherHeroIcon: { width: 52, height: 52, borderRadius: 8, backgroundColor: '#25518D', alignItems: 'center', justifyContent: 'center' },
  teacherHeroTitle: { color: COLORS.white, fontSize: 20, fontWeight: '800', marginTop: 6 },
  teacherHeroText: { color: '#D7E7FC', fontSize: 12, lineHeight: 18, marginTop: 5 },
  timeBadge: { backgroundColor: '#25518D', borderRadius: 8, height: 36, paddingHorizontal: 10, justifyContent: 'center' },
  timeBadgeText: { color: COLORS.white, fontWeight: '800', fontSize: 12 },
  attendanceCta: { height: 46, backgroundColor: COLORS.white, marginTop: 20, borderRadius: 7, alignItems: 'center', paddingHorizontal: 13, flexDirection: 'row', gap: 10 },
  attendanceCtaText: { color: COLORS.navy, fontWeight: '800', flex: 1, fontSize: 14 },
  qrSessionCard: { marginHorizontal: 20, marginTop: 14, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 14, flexDirection: 'row', gap: 14, alignItems: 'center' },
  qrCanvas: { width: 190, height: 190, borderRadius: 8, backgroundColor: COLORS.white, alignItems: 'center', justifyContent: 'center' },
  qrSessionTitle: { color: COLORS.ink, fontSize: 16, fontWeight: '800' },
  qrSessionText: { color: COLORS.muted, fontSize: 12, marginTop: 5 },
  studentPass: { marginHorizontal: 20, backgroundColor: COLORS.navy, borderRadius: 8, padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  qrMini: { width: 72, height: 72, borderRadius: 8, backgroundColor: COLORS.white, alignItems: 'center', justifyContent: 'center' },
  scanCta: { minHeight: 76, backgroundColor: COLORS.green, borderRadius: 8, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  scanCtaTitle: { color: COLORS.white, fontSize: 15, fontWeight: '800' },
  scanCtaText: { color: '#DFF5EC', fontSize: 12, marginTop: 3 },
  scannerCard: { height: 260, borderRadius: 8, overflow: 'hidden', backgroundColor: COLORS.ink },
  cameraPreview: { flex: 1 },
  scannerClose: { position: 'absolute', top: 12, right: 12, width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(16,34,63,0.82)', alignItems: 'center', justifyContent: 'center' },
  adminHero: { marginHorizontal: 20, backgroundColor: COLORS.navy, borderRadius: 8, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 },
  sectionTitle: { color: COLORS.ink, fontSize: 17, fontWeight: '800', marginTop: 25, marginBottom: 12 },
  statsRow: { flexDirection: 'row', gap: 10 },
  statCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 11, flex: 1, minHeight: 116 },
  statIcon: { width: 33, height: 33, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  statValue: { color: COLORS.ink, fontSize: 20, fontWeight: '800', marginTop: 11 },
  statLabel: { color: COLORS.muted, fontSize: 11, fontWeight: '600', marginTop: 2 },
  quickList: { backgroundColor: COLORS.white, borderColor: COLORS.line, borderWidth: 1, borderRadius: 8 },
  quickRow: { minHeight: 74, paddingHorizontal: 13, alignItems: 'center', flexDirection: 'row', gap: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line },
  quickIcon: { backgroundColor: COLORS.paper, width: 39, height: 39, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  quickTitle: { fontSize: 14, fontWeight: '800', color: COLORS.ink },
  quickSubtitle: { fontSize: 12, color: COLORS.muted, marginTop: 3 },
  tabBar: { minHeight: 69, backgroundColor: COLORS.white, borderTopWidth: 1, borderColor: COLORS.line, flexDirection: 'row', paddingHorizontal: 8, paddingTop: 8, paddingBottom: 8 },
  tabItem: { alignItems: 'center', justifyContent: 'center', flex: 1, gap: 3 },
  tabLabel: { fontSize: 10, color: COLORS.muted, fontWeight: '600' },
  tabLabelActive: { color: COLORS.blue, fontWeight: '800' },
  iconButton: { width: 42, height: 42, borderRadius: 8, backgroundColor: COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  qrButton: { width: 42, height: 42, borderRadius: 8, backgroundColor: COLORS.navy, alignItems: 'center', justifyContent: 'center' },
  searchBox: { height: 47, marginHorizontal: 20, marginBottom: 12, flexDirection: 'row', gap: 9, alignItems: 'center', paddingHorizontal: 13, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, backgroundColor: COLORS.white },
  searchInput: { flex: 1, fontSize: 14, color: COLORS.ink },
  listPad: { paddingHorizontal: 20, paddingBottom: 98, gap: 9 },
  personRow: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, minHeight: 76, borderRadius: 8, padding: 11, alignItems: 'center', flexDirection: 'row', gap: 10 },
  avatar: { width: 39, height: 39, borderRadius: 20, backgroundColor: '#E4EEFF', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: COLORS.navy, fontWeight: '800', fontSize: 12 },
  personName: { color: COLORS.ink, fontSize: 14, fontWeight: '800' },
  personMeta: { color: COLORS.muted, fontSize: 12, marginTop: 3 },
  personCareer: { color: COLORS.muted, fontSize: 11, marginTop: 2 },
  rowIconButton: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
  empty: { paddingVertical: 45, alignItems: 'center', gap: 10 },
  emptyText: { color: COLORS.muted, fontSize: 14 },
  formPanel: { position: 'absolute', zIndex: 4, left: 12, right: 12, top: 98, maxHeight: '78%', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, elevation: 4 },
  formPanelContent: { padding: 16 },
  formHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  formTitle: { fontSize: 18, fontWeight: '800', color: COLORS.ink },
  floatingActions: { position: 'absolute', alignSelf: 'center', flexDirection: 'row', gap: 10 },
  floatingBack: { height: 45, borderRadius: 8, paddingHorizontal: 17, gap: 8, flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.navy },
  floatingLogout: { height: 45, borderRadius: 8, paddingHorizontal: 17, justifyContent: 'center', backgroundColor: COLORS.red },
  floatingBackText: { color: COLORS.white, fontSize: 14, fontWeight: '800' },
  courseCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 13, flexDirection: 'row', gap: 11, marginBottom: 9 },
  teacherCourseCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 13, flexDirection: 'row', gap: 11, marginBottom: 9, alignItems: 'center' },
  courseIcon: { width: 41, height: 41, borderRadius: 8, backgroundColor: '#E6F7F0', alignItems: 'center', justifyContent: 'center' },
  courseCode: { color: COLORS.green, fontSize: 11, fontWeight: '800', letterSpacing: 0.3 },
  courseName: { color: COLORS.ink, fontSize: 15, fontWeight: '800', marginTop: 3 },
  courseMeta: { color: COLORS.muted, fontSize: 12, marginTop: 5 },
  courseStudents: { color: COLORS.muted, fontSize: 11, marginTop: 4 },
  courseSelector: { gap: 9 },
  horizontalChoices: { gap: 9, paddingBottom: 12 },
  courseChoice: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 13 },
  courseChoiceActive: { borderColor: COLORS.blue, backgroundColor: '#E8F1FF' },
  courseChoiceCode: { color: COLORS.green, fontSize: 11, fontWeight: '800' },
  courseChoiceCodeActive: { color: COLORS.blue },
  courseChoiceName: { color: COLORS.ink, fontSize: 15, fontWeight: '800', marginTop: 3 },
  courseChoiceNameActive: { color: COLORS.navy },
  courseChoiceMeta: { color: COLORS.muted, fontSize: 12, marginTop: 4 },
  courseChoiceMetaActive: { color: COLORS.blue, fontWeight: '700' },
  checkBox: { width: 30, height: 30, borderRadius: 8, borderWidth: 1, borderColor: COLORS.line, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.white },
  checkBoxActive: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  attendanceControlCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 13, gap: 12 },
  classInfoCompact: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  classInfo: { marginHorizontal: 20, padding: 13, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  classInfoTitle: { color: COLORS.ink, fontWeight: '800', fontSize: 14 },
  classInfoMeta: { color: COLORS.muted, marginTop: 4, fontSize: 12 },
  attendanceSummary: { margin: 20, paddingVertical: 15, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  summaryNumber: { color: COLORS.green, fontSize: 22, fontWeight: '800', textAlign: 'center' },
  summaryLabel: { color: COLORS.muted, fontSize: 11, fontWeight: '600', textAlign: 'center', marginTop: 3 },
  summaryDivider: { width: 1, height: 31, backgroundColor: COLORS.line },
  tip: { color: COLORS.muted, fontSize: 12, marginHorizontal: 20, marginBottom: 10 },
  tipInline: { color: COLORS.muted, fontSize: 12, marginBottom: 10 },
  attendanceRow: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, minHeight: 66, borderRadius: 8, padding: 11, alignItems: 'center', flexDirection: 'row', gap: 10 },
  statusPill: { minWidth: 76, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 9 },
  statusText: { fontSize: 11, fontWeight: '800' },
  presentPill: { backgroundColor: '#E2F6EE' },
  presentText: { color: COLORS.green },
  latePill: { backgroundColor: '#FFF2D8' },
  lateText: { color: '#AA6C00' },
  absentPill: { backgroundColor: '#FDE7E7' },
  absentText: { color: COLORS.red },
  pendingPill: { backgroundColor: '#EEF2F7' },
  pendingText: { color: COLORS.muted },
  saveSession: { margin: 14, height: 51, borderRadius: 8, backgroundColor: COLORS.blue, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  reportHero: { backgroundColor: COLORS.navy, borderRadius: 8, padding: 20 },
  reportCaption: { color: '#B5D5FF', fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
  reportValue: { color: COLORS.white, fontSize: 43, fontWeight: '800', marginTop: 4 },
  reportSubtext: { color: '#D7E7FC', fontSize: 12 },
  progressTrack: { height: 8, borderRadius: 4, overflow: 'hidden', backgroundColor: '#28528D', marginTop: 18 },
  progressFill: { height: '100%', backgroundColor: COLORS.cyan, borderRadius: 4 },
  reportGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  reportMetric: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 13, width: '47.9%' },
  reportMetricValue: { fontSize: 23, fontWeight: '800' },
  reportMetricLabel: { fontSize: 11, fontWeight: '600', color: COLORS.muted, marginTop: 4 },
  noticeRow: { minHeight: 62, paddingHorizontal: 13, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 8 },
  noticeDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: COLORS.amber },
  profileCard: { marginHorizontal: 20, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, alignItems: 'center', padding: 20 },
  profileAvatar: { width: 74, height: 74, borderRadius: 37, backgroundColor: '#E4EEFF', alignItems: 'center', justifyContent: 'center' },
  profileAvatarText: { color: COLORS.navy, fontWeight: '800', fontSize: 20 },
  profileName: { color: COLORS.ink, fontWeight: '800', fontSize: 18, marginTop: 12 },
  profileMeta: { color: COLORS.muted, fontSize: 13, marginTop: 3 },
  profileRows: { alignSelf: 'stretch', marginTop: 20, borderTopWidth: 1, borderTopColor: COLORS.line },
  infoRow: { minHeight: 48, borderBottomWidth: 1, borderBottomColor: COLORS.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  infoLabel: { color: COLORS.muted, fontSize: 13, fontWeight: '700' },
  infoValue: { color: COLORS.ink, fontSize: 13, fontWeight: '800', flex: 1, textAlign: 'right' },
});
